export type Project = { slug: string; title: string; client: string; category: string; year: string; url?: string; problem: string; answer: string; build: string[]; tone: 'museum'|'hotel'|'restaurant'|'shop'|'artist'|'story'|'street' }

export const projects: Project[] = [
  { slug:'vortex', title:'Vortex Automotive Museum', client:'Projet expérimental', category:'Culture / collection', year:'2026', url:'https://vortex13.netlify.app', problem:'Faire ressentir une collection automobile avant même de lire une fiche technique.', answer:'Un musée éditorial où chaque véhicule prend le temps d’exister, avec une navigation pensée comme une visite.', build:['Direction artistique','Parcours narratif','Interfaces immersives'], tone:'museum' },
  { slug:'saint-jules', title:'Maison Saint-Jules', client:'Projet d’hospitalité', category:'Hospitalité', year:'2026', url:'https://saintjules.netlify.app', problem:'Donner envie de séjourner, sans réduire le lieu à une grille de chambres et de tarifs.', answer:'Une présence calme et cinématographique qui installe une atmosphère avant de présenter les suites et les bains.', build:['Architecture éditoriale','Motion design','Responsive sur mesure'], tone:'hotel' },
  { slug:'heritage', title:'Heritage Restaurant', client:'Projet de restaurant', category:'Restauration', year:'2026', url:'https://heritage-restaurant.netlify.app', problem:'Mettre une table en valeur sans tomber dans le menu numérique froid ou l’imagerie de banque.', answer:'Un rythme de marque construit autour du geste, du goût et de la réservation comme prolongement naturel.', build:['Identité web','Parcours de réservation','Mise en scène du menu'], tone:'restaurant' },
  { slug:'pyjamas', title:'Maison des Pyjamas', client:'Marque e-commerce', category:'Commerce', year:'2026', url:'https://pyjamas25.netlify.app', problem:'Rendre simple la découverte d’un catalogue familial et la gestion quotidienne de la boutique.', answer:'Une vitrine chaleureuse doublée d’un espace administrable : collections, tailles, promotions et commandes restent lisibles.', build:['Catalogue produit','Interface d’administration','Paiement à connecter'], tone:'shop' },
  { slug:'emma', title:'Emma.illustre', client:'Portfolio d’artiste', category:'Création', year:'2026', url:'https://emma85.netlify.app', problem:'Présenter un travail d’illustration sans que l’interface vole la place aux œuvres.', answer:'Un portfolio papier et encre, où les catégories et les textes accompagnent le regard au lieu de le diriger.', build:['Curation des œuvres','Navigation mobile','Identité éditoriale'], tone:'artist' },
  { slug:'nounours', title:'Inspecteur Nounours', client:'Cadeau narratif', category:'Récit interactif', year:'2026', problem:'Transformer un cadeau d’anniversaire en parcours personnel plutôt qu’en simple page de félicitations.', answer:'Une enquête à explorer, faite d’indices, de personnages et de transitions conçues pour faire sourire et surprendre.', build:['Storytelling','Interactions','Expérience responsive'], tone:'story' },
  { slug:'zion', title:'ZION', client:'Marque streetwear', category:'Mode / culture', year:'2026', url:'https://zion0.netlify.app', problem:'Faire de l’identité d’une marque le point de départ du site, et pas une décoration ajoutée après coup.', answer:'Une présence plus tranchée, construite autour de l’héritage, de la fierté et de la pièce phare BUZZOFF.', build:['Positionnement','Direction visuelle','E-commerce à prolonger'], tone:'street' },
]

export const offers = [
  ['Site vitrine stratégique','Pour une activité solide dont le site ne raconte pas encore la bonne histoire. On clarifie votre offre, on construit la confiance et on donne un chemin net vers le contact.'],
  ['Portfolio ou univers créatif','Pour les artistes, architectes, marques et projets culturels qui ne peuvent pas ressembler à la concurrence. Le contenant devient une partie du message.'],
  ['Refonte complète','Pour un site devenu confus, lent ou simplement dépassé. On repart de ce qui compte : ce que vous vendez, à qui, et la perception que vous devez créer.'],
  ['Boutique, catalogue ou outil interne','Pour faire découvrir, gérer ou vendre plus simplement. Cela peut aller d’un catalogue clair à une interface métier légère, sans surcharger votre quotidien.'],
  ['Automatisation utile','Pour supprimer les tâches répétitives : centraliser une demande, faire circuler une information, suivre une action. Le but n’est jamais d’automatiser pour faire joli.'],
]
